version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Vite default port
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    command: npm run start